
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyagsvyrwgmmdmwdbzla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5YWdzdnlyd2dtbWRtd2RiemxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxOTE3NDYsImV4cCI6MjA1NTc2Nzc0Nn0.uZoZ9iGS4RDA74tBy2aOPNtNuoo7bAlvxkusdPLGQkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
